### PR TITLE
Add codeowner and publications

### PR DESCRIPTION
**Pull request by SamuelRiedel**
Update the codeowners with the current maintainers and add a list of publications and chips related to MemPool.

## Checklist

- [x] Automated tests pass
- [x] Changelog updated
- [x] Code style guideline is observed

### CODE REVIEW

**Review by mbertuletti — APPROVED** [review]
This is good.

**Comment by sermazz** [comment]
Awesome. Looks good to me.

**Comment by yichao-zh** [comment]
Good for me

**Review by yichao-zh — APPROVED** [review]
Good for me

**Pull request merged**
